// Generated by pnpm stats-tiles:generate from shared/stats-tiles.json. Do not edit by hand.

enum StatsTileID: String, CaseIterable, Hashable, Sendable {
    case thisWeek
    case weeklyVolume
    case typicalWeek
    case yearToDate
    case yearPace
    case monthVsLastMonth
    case records
    case totals
    case activityCalendar
    case consistency
    case sportMix
    case distanceVsElevation
    case speedTrend
}

enum StatsMetric: String, CaseIterable, Hashable, Sendable {
    case count
    case distance
    case elevation
    case time

    struct Definition: Hashable, Sendable {
        let label: String
        let unit: String
    }

    var definition: Definition {
        switch self {
        case .count: return .init(label: "Activities", unit: "")
        case .distance: return .init(label: "Distance", unit: "km")
        case .elevation: return .init(label: "Elevation", unit: "m")
        case .time: return .init(label: "Moving time", unit: "h")
        }
    }
}

enum StatsTileGroup: String, CaseIterable, Hashable, Sendable {
    case now
    case thisYear
    case patterns

    var title: String {
        switch self {
        case .now: return "Now"
        case .thisYear: return "This year"
        case .patterns: return "Patterns"
        }
    }
}

enum StatsWindow: String, CaseIterable, Hashable, Sendable {
    case currentWeek
    case yearToDate
    case currentYear
    case monthToDate
    case last12Weeks
    case last52Weeks
    case last12Months
    case allTime
}

enum StatsToggleOption: String, CaseIterable, Hashable, Sendable {
    case count
    case distance
    case elevation
    case time
    case currentWeek
    case yearToDate
    case currentYear
    case monthToDate
    case last12Weeks
    case last52Weeks
    case last12Months
    case allTime
    case sport
}

struct StatsTileSpan: Hashable, Sendable {
    let columns: Int
    let rows: Int
}

struct StatsTileToggle: Hashable, Sendable {
    let label: String
    let options: [StatsToggleOption]
}

struct StatsTileDefinition: Identifiable, Hashable, Sendable {
    let id: StatsTileID
    let title: String
    let window: StatsWindow
    let group: StatsTileGroup
    let isPrimary: Bool
    let span: StatsTileSpan
    let isOptional: Bool
    let toggle: StatsTileToggle?
}

struct StatsGridDefinition: Hashable, Sendable {
    let columns: Int
    let rowHeight: Double
}

enum SharedStatsTiles {
    static let regularGrid = StatsGridDefinition(columns: 4, rowHeight: 168)
    static let regularMinWidth: Double = 720
    static let compactGrid = StatsGridDefinition(columns: 2, rowHeight: 156)
    static let gap: Double = 12

    static let tiles: [StatsTileDefinition] = [
        .init(
            id: .thisWeek,
            title: "This week",
            window: .currentWeek,
            group: .now,
            isPrimary: false,
            span: .init(columns: 1, rows: 1),
            isOptional: false,
            toggle: .init(label: "Metric", options: [.distance, .time, .elevation])
        ),
        .init(
            id: .weeklyVolume,
            title: "Training volume",
            window: .last12Weeks,
            group: .now,
            isPrimary: true,
            span: .init(columns: 2, rows: 1),
            isOptional: false,
            toggle: .init(label: "Metric", options: [.distance, .elevation, .time, .count])
        ),
        .init(
            id: .typicalWeek,
            title: "Typical week",
            window: .last12Weeks,
            group: .now,
            isPrimary: false,
            span: .init(columns: 1, rows: 1),
            isOptional: false,
            toggle: nil
        ),
        .init(
            id: .yearToDate,
            title: "Year to date",
            window: .yearToDate,
            group: .thisYear,
            isPrimary: true,
            span: .init(columns: 2, rows: 2),
            isOptional: false,
            toggle: .init(label: "Metric", options: [.distance, .elevation, .time, .count])
        ),
        .init(
            id: .yearPace,
            title: "Pace",
            window: .yearToDate,
            group: .thisYear,
            isPrimary: false,
            span: .init(columns: 1, rows: 1),
            isOptional: false,
            toggle: .init(label: "Metric", options: [.distance, .time, .elevation])
        ),
        .init(
            id: .monthVsLastMonth,
            title: "This month",
            window: .monthToDate,
            group: .thisYear,
            isPrimary: false,
            span: .init(columns: 1, rows: 1),
            isOptional: false,
            toggle: .init(label: "Metric", options: [.elevation, .distance, .time, .count])
        ),
        .init(
            id: .records,
            title: "Records",
            window: .currentYear,
            group: .thisYear,
            isPrimary: false,
            span: .init(columns: 2, rows: 1),
            isOptional: false,
            toggle: nil
        ),
        .init(
            id: .totals,
            title: "Totals",
            window: .currentYear,
            group: .thisYear,
            isPrimary: false,
            span: .init(columns: 2, rows: 1),
            isOptional: true,
            toggle: .init(label: "Metric", options: [.count, .distance, .elevation, .time])
        ),
        .init(
            id: .activityCalendar,
            title: "Activity calendar",
            window: .last12Months,
            group: .patterns,
            isPrimary: false,
            span: .init(columns: 2, rows: 1),
            isOptional: false,
            toggle: .init(label: "Colour by", options: [.sport, .distance, .elevation, .time])
        ),
        .init(
            id: .consistency,
            title: "Consistency",
            window: .last12Weeks,
            group: .patterns,
            isPrimary: false,
            span: .init(columns: 1, rows: 1),
            isOptional: false,
            toggle: .init(label: "Range", options: [.last12Weeks, .last52Weeks])
        ),
        .init(
            id: .sportMix,
            title: "Sport mix",
            window: .currentYear,
            group: .patterns,
            isPrimary: false,
            span: .init(columns: 1, rows: 1),
            isOptional: false,
            toggle: .init(label: "Range", options: [.currentYear, .allTime])
        ),
        .init(
            id: .distanceVsElevation,
            title: "Climbing",
            window: .last12Months,
            group: .patterns,
            isPrimary: false,
            span: .init(columns: 2, rows: 1),
            isOptional: false,
            toggle: nil
        ),
        .init(
            id: .speedTrend,
            title: "Speed trend",
            window: .last12Months,
            group: .patterns,
            isPrimary: false,
            span: .init(columns: 1, rows: 1),
            isOptional: true,
            toggle: .init(label: "Range", options: [.last12Months, .allTime])
        )
    ]
}
