// Generated by pnpm stats-tiles:generate from shared/stats-tiles.json. Do not edit by hand.

enum StatsTileID: String, CaseIterable, Hashable, Sendable {
    case yearToDate
    case totals
    case weeklyVolume
    case activityCalendar
    case monthVsLastMonth
    case sportMix
    case consistency
    case distanceVsElevation
    case speedTrend
}

enum StatsMetric: String, CaseIterable, Hashable, Sendable {
    case count
    case distance
    case elevation
    case time

    struct Definition: Hashable, Sendable {
        let label: String
        let unit: String
    }

    var definition: Definition {
        switch self {
        case .count: return .init(label: "Activities", unit: "")
        case .distance: return .init(label: "Distance", unit: "km")
        case .elevation: return .init(label: "Elevation", unit: "m")
        case .time: return .init(label: "Moving time", unit: "h")
        }
    }
}

enum StatsWindow: String, CaseIterable, Hashable, Sendable {
    case yearToDate
    case currentYear
    case monthToDate
    case last12Weeks
    case last52Weeks
    case last12Months
    case allTime
}

enum StatsToggleOption: String, CaseIterable, Hashable, Sendable {
    case count
    case distance
    case elevation
    case time
    case yearToDate
    case currentYear
    case monthToDate
    case last12Weeks
    case last52Weeks
    case last12Months
    case allTime
    case sport
}

struct StatsTileSpan: Hashable, Sendable {
    let columns: Int
    let rows: Int
}

struct StatsTileToggle: Hashable, Sendable {
    let label: String
    let options: [StatsToggleOption]
}

struct StatsTileDefinition: Identifiable, Hashable, Sendable {
    let id: StatsTileID
    let title: String
    let window: StatsWindow
    let span: StatsTileSpan
    let isOptional: Bool
    let toggle: StatsTileToggle?
}

struct StatsGridDefinition: Hashable, Sendable {
    let columns: Int
    let rowHeight: Double
}

enum SharedStatsTiles {
    static let regularGrid = StatsGridDefinition(columns: 4, rowHeight: 168)
    static let regularMinWidth: Double = 720
    static let compactGrid = StatsGridDefinition(columns: 2, rowHeight: 156)
    static let gap: Double = 12

    static let tiles: [StatsTileDefinition] = [
        .init(
            id: .yearToDate,
            title: "Year to date",
            window: .yearToDate,
            span: .init(columns: 2, rows: 2),
            isOptional: false,
            toggle: .init(label: "Metric", options: [.distance, .elevation, .time, .count])
        ),
        .init(
            id: .totals,
            title: "Totals",
            window: .currentYear,
            span: .init(columns: 2, rows: 1),
            isOptional: false,
            toggle: .init(label: "Metric", options: [.count, .distance, .elevation, .time])
        ),
        .init(
            id: .weeklyVolume,
            title: "Weekly volume",
            window: .last12Weeks,
            span: .init(columns: 2, rows: 1),
            isOptional: false,
            toggle: .init(label: "Metric", options: [.distance, .elevation, .time, .count])
        ),
        .init(
            id: .activityCalendar,
            title: "Activity calendar",
            window: .last12Months,
            span: .init(columns: 2, rows: 1),
            isOptional: false,
            toggle: .init(label: "Colour by", options: [.sport, .distance, .elevation, .time])
        ),
        .init(
            id: .monthVsLastMonth,
            title: "This month",
            window: .monthToDate,
            span: .init(columns: 1, rows: 1),
            isOptional: false,
            toggle: .init(label: "Metric", options: [.elevation, .distance, .time, .count])
        ),
        .init(
            id: .sportMix,
            title: "Sport mix",
            window: .currentYear,
            span: .init(columns: 1, rows: 1),
            isOptional: false,
            toggle: .init(label: "Range", options: [.currentYear, .allTime])
        ),
        .init(
            id: .consistency,
            title: "Consistency",
            window: .last12Weeks,
            span: .init(columns: 1, rows: 1),
            isOptional: false,
            toggle: .init(label: "Range", options: [.last12Weeks, .last52Weeks])
        ),
        .init(
            id: .distanceVsElevation,
            title: "Distance vs elevation",
            window: .last12Months,
            span: .init(columns: 2, rows: 1),
            isOptional: false,
            toggle: nil
        ),
        .init(
            id: .speedTrend,
            title: "Speed trend",
            window: .last12Months,
            span: .init(columns: 1, rows: 1),
            isOptional: true,
            toggle: .init(label: "Range", options: [.last12Months, .allTime])
        )
    ]
}
