// Generated by pnpm api-dtos:generate. Do not edit by hand.
//
// Swift mirrors of the v1 wire contract in src/contracts/v1, produced from the
// same Zod schemas the Route Handlers validate against. Companion hand-written
// types (the response envelope, paged lists, JSONValue, and the decoder) live
// in APISupport.swift.
//
// Unknown JSON keys are ignored on decode, so an older build keeps working
// against a server that has added fields.
//
// Everything here is nonisolated: the target builds with
// SWIFT_DEFAULT_ACTOR_ISOLATION = MainActor, and the sync engine decodes these
// on its own background actor.

import Foundation

nonisolated enum ActivityMapAPI {
    /// Matches SCHEMA_VERSION in src/contracts/v1/primitives.ts. Every v1
    /// response carries this; anything else means the contracts have diverged.
    static let schemaVersion = "1"
}

nonisolated extension ActivityMapAPI {
    struct StreamMetadata: Codable, Hashable, Sendable {
        let generation: String?
        let revision: String
        let state: StreamFreshness
        let fetchStatus: StreamFetchStatus
        let availableTypes: [StreamType]
        let fetchedAt: Date?
        let expiresAt: Date?

        enum CodingKeys: String, CodingKey {
            case generation
            case revision
            case state
            case fetchStatus = "fetch_status"
            case availableTypes = "available_types"
            case fetchedAt = "fetched_at"
            case expiresAt = "expires_at"
        }
    }

    struct TimeStream: Codable, Hashable, Sendable {
        let type: String?
        let data: [Int]
        let originalSize: Int
        let resolution: StreamResolution
        let seriesType: StreamSeriesType

        enum CodingKeys: String, CodingKey {
            case type
            case data
            case originalSize = "original_size"
            case resolution
            case seriesType = "series_type"
        }
    }

    struct DistanceStream: Codable, Hashable, Sendable {
        let type: String?
        let data: [Double]
        let originalSize: Int
        let resolution: StreamResolution
        let seriesType: StreamSeriesType

        enum CodingKeys: String, CodingKey {
            case type
            case data
            case originalSize = "original_size"
            case resolution
            case seriesType = "series_type"
        }
    }

    struct LatlngStream: Codable, Hashable, Sendable {
        let type: String?
        let data: [[Double]]
        let originalSize: Int
        let resolution: StreamResolution
        let seriesType: StreamSeriesType

        enum CodingKeys: String, CodingKey {
            case type
            case data
            case originalSize = "original_size"
            case resolution
            case seriesType = "series_type"
        }
    }

    struct AltitudeStream: Codable, Hashable, Sendable {
        let type: String?
        let data: [Double]
        let originalSize: Int
        let resolution: StreamResolution
        let seriesType: StreamSeriesType

        enum CodingKeys: String, CodingKey {
            case type
            case data
            case originalSize = "original_size"
            case resolution
            case seriesType = "series_type"
        }
    }

    struct WattsStream: Codable, Hashable, Sendable {
        let type: String?
        let data: [Int]
        let originalSize: Int
        let resolution: StreamResolution
        let seriesType: StreamSeriesType

        enum CodingKeys: String, CodingKey {
            case type
            case data
            case originalSize = "original_size"
            case resolution
            case seriesType = "series_type"
        }
    }

    struct HeartrateStream: Codable, Hashable, Sendable {
        let type: String?
        let data: [Int]
        let originalSize: Int
        let resolution: StreamResolution
        let seriesType: StreamSeriesType

        enum CodingKeys: String, CodingKey {
            case type
            case data
            case originalSize = "original_size"
            case resolution
            case seriesType = "series_type"
        }
    }

    struct RawStreams: Codable, Hashable, Sendable {
        let time: TimeStream?
        let distance: DistanceStream?
        let latlng: LatlngStream?
        let altitude: AltitudeStream?
        let watts: WattsStream?
        let heartrate: HeartrateStream?
    }

    /// The shape of `ActivityStreams.last_error`.
    struct ActivityStreamsLastError: Codable, Hashable, Sendable {
        let code: StreamFailureCode
        let retryable: Bool
    }

    struct ActivityStreams: Codable, Hashable, Sendable {
        let activityID: String
        let metadata: StreamMetadata
        let requestedTypes: [StreamType]
        let streams: RawStreams?
        let lastError: ActivityStreamsLastError?
        let nextRetryAt: Date?

        enum CodingKeys: String, CodingKey {
            case activityID = "activity_id"
            case metadata
            case requestedTypes = "requested_types"
            case streams
            case lastError = "last_error"
            case nextRetryAt = "next_retry_at"
        }
    }

    struct Authentication: Codable, Hashable, Sendable {
        let method: AuthenticationMethod
        let sessionExpiresAt: Date
    }

    struct CurrentUser: Codable, Hashable, Sendable {
        let id: String
        let name: String?
        let email: String?
        let image: String?
        let athleteID: String?
        let stravaConnected: Bool
        let authentication: Authentication

        enum CodingKeys: String, CodingKey {
            case id
            case name
            case email
            case image
            case athleteID = "athleteId"
            case stravaConnected
            case authentication
        }
    }

    struct Activity: Codable, Hashable, Sendable {
        let streams: StreamMetadata?
        let id: String
        let athlete: String
        let name: String
        let description: String?
        let distance: Double?
        let movingTime: Int?
        let elapsedTime: Int?
        let totalElevationGain: Double?
        let sportType: SportType
        let startDate: Date
        let startDateLocal: Date
        let timezone: String
        let startLatlng: [Double]?
        let endLatlng: [Double]?
        let achievementCount: Int?
        let kudosCount: Int?
        let commentCount: Int?
        let athleteCount: Int?
        let photoCount: Int?
        let totalPhotoCount: Int?
        let mapID: String?
        let mapPolyline: String?
        let mapSummaryPolyline: String?
        let mapBbox: [Double]?
        let trainer: Bool?
        let commute: Bool?
        let manual: Bool?
        let `private`: Bool?
        let flagged: Bool?
        let workoutType: Int?
        let uploadID: String?
        let averageSpeed: Double?
        let maxSpeed: Double?
        let calories: Double?
        let hasHeartrate: Bool?
        let averageHeartrate: Double?
        let maxHeartrate: Double?
        let heartrateOptOut: Bool?
        let displayHideHeartrateOption: Bool?
        let elevHigh: Double?
        let elevLow: Double?
        let prCount: Int?
        let hasKudoed: Bool?
        let hideFromHome: Bool?
        let gearID: String?
        let deviceWatts: Bool?
        let averageWatts: Double?
        let maxWatts: Int?
        let weightedAverageWatts: Int?
        let kilojoules: Double?
        let lastUpdated: Date?
        let geometryState: GeometryState
        let photosState: PhotosState?
        let lastSummarySeenAt: Date?
        let lastDetailedFetchedAt: Date?

        enum CodingKeys: String, CodingKey {
            case streams
            case id
            case athlete
            case name
            case description
            case distance
            case movingTime = "moving_time"
            case elapsedTime = "elapsed_time"
            case totalElevationGain = "total_elevation_gain"
            case sportType = "sport_type"
            case startDate = "start_date"
            case startDateLocal = "start_date_local"
            case timezone
            case startLatlng = "start_latlng"
            case endLatlng = "end_latlng"
            case achievementCount = "achievement_count"
            case kudosCount = "kudos_count"
            case commentCount = "comment_count"
            case athleteCount = "athlete_count"
            case photoCount = "photo_count"
            case totalPhotoCount = "total_photo_count"
            case mapID = "map_id"
            case mapPolyline = "map_polyline"
            case mapSummaryPolyline = "map_summary_polyline"
            case mapBbox = "map_bbox"
            case trainer
            case commute
            case manual
            case `private`
            case flagged
            case workoutType = "workout_type"
            case uploadID = "upload_id"
            case averageSpeed = "average_speed"
            case maxSpeed = "max_speed"
            case calories
            case hasHeartrate = "has_heartrate"
            case averageHeartrate = "average_heartrate"
            case maxHeartrate = "max_heartrate"
            case heartrateOptOut = "heartrate_opt_out"
            case displayHideHeartrateOption = "display_hide_heartrate_option"
            case elevHigh = "elev_high"
            case elevLow = "elev_low"
            case prCount = "pr_count"
            case hasKudoed = "has_kudoed"
            case hideFromHome = "hide_from_home"
            case gearID = "gear_id"
            case deviceWatts = "device_watts"
            case averageWatts = "average_watts"
            case maxWatts = "max_watts"
            case weightedAverageWatts = "weighted_average_watts"
            case kilojoules
            case lastUpdated = "last_updated"
            case geometryState = "geometry_state"
            case photosState = "photos_state"
            case lastSummarySeenAt = "last_summary_seen_at"
            case lastDetailedFetchedAt = "last_detailed_fetched_at"
        }
    }

    struct Photo: Codable, Hashable, Sendable {
        let uniqueID: String
        let activityID: String
        let athleteID: String
        let activityName: String?
        let caption: String?
        let type: Int
        let source: Int?
        let urls: [String: String]?
        let sizes: [String: [Double]]?
        let defaultPhoto: Bool?
        let location: [Double]?
        let uploadedAt: Date?
        let createdAt: Date?
        let postID: Int?
        let status: String?
        let resourceState: Int?

        enum CodingKeys: String, CodingKey {
            case uniqueID = "unique_id"
            case activityID = "activity_id"
            case athleteID = "athlete_id"
            case activityName = "activity_name"
            case caption
            case type
            case source
            case urls
            case sizes
            case defaultPhoto = "default_photo"
            case location
            case uploadedAt = "uploaded_at"
            case createdAt = "created_at"
            case postID = "post_id"
            case status
            case resourceState = "resource_state"
        }
    }

    struct SyncRetentionMeta: Codable, Hashable, Sendable {
        let retentionDays: Int
        let cursorValidUntil: Date
    }

    struct SyncFreshnessMeta: Codable, Hashable, Sendable {
        let lastSummaryReconciledAt: Date?
    }

    struct SyncChangeItem: Codable, Hashable, Sendable {
        let sequence: String
        let entityType: EntityType
        let operation: ChangeOperation
        let id: String
        let activity: Activity?
        let photo: Photo?
    }

    /// The `activities` variant of `SyncBootstrapPage`.
    struct SyncBootstrapPageActivities: Codable, Hashable, Sendable {
        let items: [Activity]
        let nextCursor: String?
        let snapshotCursor: String?
        let retention: SyncRetentionMeta
        let freshness: SyncFreshnessMeta
    }

    /// The `photos` variant of `SyncBootstrapPage`.
    struct SyncBootstrapPagePhotos: Codable, Hashable, Sendable {
        let items: [Photo]
        let nextCursor: String?
        let snapshotCursor: String?
        let retention: SyncRetentionMeta
        let freshness: SyncFreshnessMeta
    }

    enum SyncBootstrapPage: Decodable, Hashable, Sendable {
        case activities(SyncBootstrapPageActivities)
        case photos(SyncBootstrapPagePhotos)

        private enum DiscriminatorKeys: String, CodingKey {
            case resource = "resource"
        }

        init(from decoder: any Decoder) throws {
            let container = try decoder.container(keyedBy: DiscriminatorKeys.self)
            let discriminator = try container.decode(String.self, forKey: .resource)
            switch discriminator {
            case "activities":
                self = .activities(try SyncBootstrapPageActivities(from: decoder))
            case "photos":
                self = .photos(try SyncBootstrapPagePhotos(from: decoder))
            default:
                throw DecodingError.dataCorrupted(
                    DecodingError.Context(
                        codingPath: decoder.codingPath,
                        debugDescription: "Unknown SyncBootstrapPage resource \(discriminator)"
                    )
                )
            }
        }
    }

    struct SyncChangesPage: Codable, Hashable, Sendable {
        let items: [SyncChangeItem]
        let nextCursor: String
        let retention: SyncRetentionMeta
        let freshness: SyncFreshnessMeta
    }

    /// The shape of `ErrorEnvelope.error`.
    struct ErrorBody: Codable, Hashable, Sendable {
        let code: String
        let message: String
        let retryable: Bool
        let requestID: String
        let details: JSONValue?

        enum CodingKeys: String, CodingKey {
            case code
            case message
            case retryable
            case requestID = "requestId"
            case details
        }
    }

    struct ErrorEnvelope: Codable, Hashable, Sendable {
        let error: ErrorBody
    }

    struct MobileExchangeRequest: Codable, Hashable, Sendable {
        let code: String
        let pkceVerifier: String
        let state: String
    }

    struct MobileExchangeResponse: Codable, Hashable, Sendable {
        let sessionToken: String
        let tokenType: String
        let sessionExpiresAt: Date
    }

    struct MobileSession: Codable, Hashable, Sendable {
        let token: String
        let createdAt: Date
        let expiresAt: Date
        let ipAddress: String?
        let userAgent: String?
        let isCurrent: Bool
    }

    struct MobileSessionList: Codable, Hashable, Sendable {
        let sessions: [MobileSession]
    }

    struct RevokeSessionRequest: Codable, Hashable, Sendable {
        let token: String
    }
}

nonisolated extension ActivityMapAPI {
    enum AuthenticationMethod: String, Codable, Hashable, Sendable {
        case cookie = "cookie"
        case bearer = "bearer"
    }

    enum ChangeOperation: String, Codable, Hashable, Sendable {
        case upsert = "upsert"
        case delete = "delete"
    }

    enum EntityType: String, Codable, Hashable, Sendable {
        case activity = "activity"
        case photo = "photo"
    }

    enum GeometryState: String, Codable, Hashable, Sendable {
        case summary = "summary"
        case detailed = "detailed"
        case refreshRequired = "refresh_required"
    }

    enum PhotosState: String, Codable, Hashable, Sendable {
        case current = "current"
        case refreshRequired = "refresh_required"
    }

    enum SportType: String, Codable, Hashable, Sendable {
        case alpineSki = "AlpineSki"
        case backcountrySki = "BackcountrySki"
        case badminton = "Badminton"
        case canoeing = "Canoeing"
        case crossfit = "Crossfit"
        case eBikeRide = "EBikeRide"
        case eMountainBikeRide = "EMountainBikeRide"
        case elliptical = "Elliptical"
        case golf = "Golf"
        case gravelRide = "GravelRide"
        case handcycle = "Handcycle"
        case highIntensityIntervalTraining = "HighIntensityIntervalTraining"
        case hike = "Hike"
        case iceSkate = "IceSkate"
        case inlineSkate = "InlineSkate"
        case kayaking = "Kayaking"
        case kitesurf = "Kitesurf"
        case mountainBikeRide = "MountainBikeRide"
        case nordicSki = "NordicSki"
        case pickleball = "Pickleball"
        case pilates = "Pilates"
        case racquetball = "Racquetball"
        case ride = "Ride"
        case rockClimbing = "RockClimbing"
        case rollerSki = "RollerSki"
        case rowing = "Rowing"
        case run = "Run"
        case sail = "Sail"
        case skateboard = "Skateboard"
        case snowboard = "Snowboard"
        case snowshoe = "Snowshoe"
        case soccer = "Soccer"
        case squash = "Squash"
        case stairStepper = "StairStepper"
        case standUpPaddling = "StandUpPaddling"
        case surfing = "Surfing"
        case swim = "Swim"
        case tableTennis = "TableTennis"
        case tennis = "Tennis"
        case trailRun = "TrailRun"
        case velomobile = "Velomobile"
        case virtualRide = "VirtualRide"
        case virtualRow = "VirtualRow"
        case virtualRun = "VirtualRun"
        case walk = "Walk"
        case weightTraining = "WeightTraining"
        case wheelchair = "Wheelchair"
        case windsurf = "Windsurf"
        case workout = "Workout"
        case yoga = "Yoga"
    }

    enum StreamFailureCode: String, Codable, Hashable, Sendable {
        case rateLimited = "rate_limited"
        case unauthorized = "unauthorized"
        case notFound = "not_found"
        case invalidResponse = "invalid_response"
        case upstreamError = "upstream_error"
    }

    enum StreamFetchStatus: String, Codable, Hashable, Sendable {
        case notFetched = "not_fetched"
        case pending = "pending"
        case succeeded = "succeeded"
        case failed = "failed"
        case invalidated = "invalidated"
    }

    enum StreamFreshness: String, Codable, Hashable, Sendable {
        case notFetched = "not_fetched"
        case current = "current"
        case stale = "stale"
    }

    enum StreamResolution: String, Codable, Hashable, Sendable {
        case low = "low"
        case medium = "medium"
        case high = "high"
    }

    enum StreamSeriesType: String, Codable, Hashable, Sendable {
        case time = "time"
        case distance = "distance"
    }

    enum StreamType: String, Codable, Hashable, Sendable {
        case time = "time"
        case distance = "distance"
        case latlng = "latlng"
        case altitude = "altitude"
        case watts = "watts"
        case heartrate = "heartrate"
    }

    enum SyncResource: String, Codable, Hashable, Sendable {
        case activities = "activities"
        case photos = "photos"
    }
}
