// Generated by pnpm map-catalog:generate. Do not edit by hand.

enum SharedBaseMapSource: Hashable, Sendable {
    case style(url: String)
    case raster(url: String, tileSize: Double)
}

struct SharedBaseMapDefinition: Identifiable, Hashable, Sendable {
    let id: String
    let label: String
    let source: SharedBaseMapSource
    let visibleByDefault: Bool
    let attribution: String?
}

struct SharedRasterOverlayDefinition: Identifiable, Hashable, Sendable {
    let id: String
    let label: String
    let url: String
    let tileSize: Double
    let visibleByDefault: Bool
    let opacity: Double
    let attribution: String?
}

enum SharedMapCatalog {
    static let baseMaps: [SharedBaseMapDefinition] = [
        .init(
            id: "mapboxStreet",
            label: "Mapbox Street",
            source: .style(url: "mapbox://styles/mapbox/streets-v12"),
            visibleByDefault: true,
            attribution: nil
        ),
        .init(
            id: "mapboxStreet3d",
            label: "Mapbox Street 3D",
            source: .style(url: "mapbox://styles/wirhabenzeit/clk6y6c1q00lk01pe8fqs0urn"),
            visibleByDefault: false,
            attribution: nil
        ),
        .init(
            id: "mapboxOutdoors",
            label: "Mapbox Outdoors",
            source: .style(url: "mapbox://styles/mapbox/outdoors-v12"),
            visibleByDefault: false,
            attribution: nil
        ),
        .init(
            id: "mapboxLight",
            label: "Mapbox Light",
            source: .style(url: "mapbox://styles/mapbox/light-v11"),
            visibleByDefault: false,
            attribution: nil
        ),
        .init(
            id: "mapboxTopolight",
            label: "Mapbox Topolight",
            source: .style(url: "mapbox://styles/wirhabenzeit/clk0tpduc00ab01qyguzi09gv"),
            visibleByDefault: false,
            attribution: nil
        ),
        .init(
            id: "mapboxDark",
            label: "Mapbox Dark",
            source: .style(url: "mapbox://styles/mapbox/dark-v11"),
            visibleByDefault: false,
            attribution: nil
        ),
        .init(
            id: "mapboxSatellite",
            label: "Mapbox Satellite",
            source: .style(url: "mapbox://styles/mapbox/satellite-v9"),
            visibleByDefault: false,
            attribution: nil
        ),
        .init(
            id: "swisstopoVectorBasemap",
            label: "Swisstopo Vector Basemap",
            source: .style(url: "https://vectortiles.geo.admin.ch/styles/ch.swisstopo.basemap.vt/style.json"),
            visibleByDefault: false,
            attribution: "© swisstopo"
        ),
        .init(
            id: "swisstopoVectorLight",
            label: "Swisstopo Vector Light",
            source: .style(url: "https://vectortiles.geo.admin.ch/styles/ch.swisstopo.lightbasemap.vt/style.json"),
            visibleByDefault: false,
            attribution: "© swisstopo"
        ),
        .init(
            id: "swisstopoVectorWinter",
            label: "Swisstopo Vector Winter",
            source: .style(url: "https://vectortiles.geo.admin.ch/styles/ch.swisstopo.basemap-winter.vt/style.json"),
            visibleByDefault: false,
            attribution: "© swisstopo"
        ),
        .init(
            id: "swisstopoSatellite",
            label: "Swisstopo Satellite",
            source: .style(url: "https://vectortiles.geo.admin.ch/styles/ch.swisstopo.leichte-basiskarte-imagery.vt/style.json"),
            visibleByDefault: false,
            attribution: "© swisstopo"
        ),
        .init(
            id: "swisstopoPixelkarte",
            label: "Swisstopo Pixelkarte",
            source: .raster(url: "https://wmts.geo.admin.ch/1.0.0/ch.swisstopo.pixelkarte-farbe/default/current/3857/{z}/{x}/{y}.jpeg", tileSize: 256),
            visibleByDefault: false,
            attribution: "© swisstopo"
        ),
        .init(
            id: "swisstopoWinter",
            label: "Swisstopo Winter",
            source: .raster(url: "https://wmts.geo.admin.ch/1.0.0/ch.swisstopo.pixelkarte-farbe-winter/default/current/3857/{z}/{x}/{y}.jpeg", tileSize: 256),
            visibleByDefault: false,
            attribution: "© swisstopo"
        ),
        .init(
            id: "norgeskart",
            label: "NorgesKart",
            source: .raster(url: "https://cache.kartverket.no/v1/wmts/1.0.0/toporaster/default/webmercator/{z}/{y}/{x}.png", tileSize: 256),
            visibleByDefault: false,
            attribution: "© Kartverket"
        )
    ]

    static let rasterOverlays: [SharedRasterOverlayDefinition] = [
        .init(
            id: "swisstopoSki",
            label: "Swisstopo Ski",
            url: "https://wmts.geo.admin.ch/1.0.0/ch.swisstopo-karto.skitouren/default/current/3857/{z}/{x}/{y}.png",
            tileSize: 256,
            visibleByDefault: false,
            opacity: 0.8,
            attribution: "© swisstopo"
        ),
        .init(
            id: "nveAvalanche",
            label: "NVE Avalanche",
            url: "https://gis3.nve.no/arcgis/rest/services/wmts/Bratthet_med_utlop_2024/MapServer/tile/{z}/{y}/{x}",
            tileSize: 256,
            visibleByDefault: false,
            opacity: 0.2,
            attribution: "© NVE"
        ),
        .init(
            id: "swisstopoSlope",
            label: "Swisstopo Slope",
            url: "https://wmts.geo.admin.ch/1.0.0/ch.swisstopo.hangneigung-ueber_30/default/current/3857/{z}/{x}/{y}.png",
            tileSize: 256,
            visibleByDefault: false,
            opacity: 0.4,
            attribution: "© swisstopo"
        ),
        .init(
            id: "veloland",
            label: "Veloland",
            url: "https://wmts.geo.admin.ch/1.0.0/ch.astra.veloland/default/current/3857/{z}/{x}/{y}.png",
            tileSize: 256,
            visibleByDefault: false,
            opacity: 0.4,
            attribution: "© swisstopo"
        ),
        .init(
            id: "wanderland",
            label: "Wanderland",
            url: "https://wmts.geo.admin.ch/1.0.0/ch.astra.wanderland/default/current/3857/{z}/{x}/{y}.png",
            tileSize: 256,
            visibleByDefault: false,
            opacity: 0.4,
            attribution: "© swisstopo"
        )
    ]
}
