#!/usr/bin/env -S tsx

import { readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { z } from 'zod';

const repositoryRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const catalogPath = resolve(repositoryRoot, 'shared/map-catalog.json');
const swiftOutputPath = resolve(
  repositoryRoot,
  'ios/ActivityMap/ActivityMap/Map/SharedMapCatalog.generated.swift',
);

const sourceURLSchema = z
  .string()
  .min(1)
  .refine(
    (url) => url.startsWith('https://') || url.startsWith('mapbox://'),
    'must use https:// or mapbox://',
  )
  .refine(
    (url) => !url.includes('access_token') && !/[?&]token=/i.test(url),
    'must not contain credentials',
  );

const commonSourceFields = {
  label: z.string().min(1),
  url: sourceURLSchema,
  visible: z.boolean(),
  attribution: z.string().min(1).optional(),
};

const baseMapSchema = z.discriminatedUnion('type', [
  z
    .object({
      ...commonSourceFields,
      type: z.literal('style'),
    })
    .strict(),
  z
    .object({
      ...commonSourceFields,
      type: z.literal('raster'),
      tileSize: z.number().int().positive(),
    })
    .strict(),
]);

const rasterOverlaySchema = z
  .object({
    label: z.string().min(1),
    url: sourceURLSchema,
    tileSize: z.number().int().positive(),
    visible: z.boolean(),
    opacity: z.number().min(0).max(1),
    attribution: z.string().min(1).optional(),
  })
  .strict();

const catalogIDSchema = z.string().regex(/^[a-z][A-Za-z0-9]*$/);
const catalogSchema = z
  .object({
    version: z.literal(1),
    baseMaps: z.record(catalogIDSchema, baseMapSchema),
    rasterOverlays: z.record(catalogIDSchema, rasterOverlaySchema),
  })
  .strict();

const rawCatalog: unknown = JSON.parse(await readFile(catalogPath, 'utf8'));
const catalog = catalogSchema.parse(rawCatalog);
const baseMaps = Object.entries(catalog.baseMaps);
const rasterOverlays = Object.entries(catalog.rasterOverlays);

if (baseMaps.length === 0) {
  throw new Error(
    'The shared map catalogue must contain at least one base map.',
  );
}

if (baseMaps.filter(([, baseMap]) => baseMap.visible).length !== 1) {
  throw new Error('Exactly one shared base map must be visible by default.');
}

const baseMapIDs = new Set(baseMaps.map(([id]) => id));
const duplicateID = rasterOverlays.find(([id]) => baseMapIDs.has(id));
if (duplicateID) {
  throw new Error(`Map catalogue ID ${duplicateID[0]} is used more than once.`);
}

const swiftString = (value: string): string => JSON.stringify(value);
const swiftOptionalString = (value: string | undefined): string =>
  value === undefined ? 'nil' : swiftString(value);

const baseMapRows = baseMaps
  .map(([id, baseMap]) => {
    const source =
      baseMap.type === 'style'
        ? `.style(url: ${swiftString(baseMap.url)})`
        : `.raster(url: ${swiftString(baseMap.url)}, tileSize: ${baseMap.tileSize})`;

    return `        .init(
            id: ${swiftString(id)},
            label: ${swiftString(baseMap.label)},
            source: ${source},
            visibleByDefault: ${baseMap.visible},
            attribution: ${swiftOptionalString(baseMap.attribution)}
        )`;
  })
  .join(',\n');

const overlayRows = rasterOverlays
  .map(
    ([id, overlay]) => `        .init(
            id: ${swiftString(id)},
            label: ${swiftString(overlay.label)},
            url: ${swiftString(overlay.url)},
            tileSize: ${overlay.tileSize},
            visibleByDefault: ${overlay.visible},
            opacity: ${overlay.opacity},
            attribution: ${swiftOptionalString(overlay.attribution)}
        )`,
  )
  .join(',\n');

const generatedSwift = `// Generated by pnpm map-catalog:generate. Do not edit by hand.

enum SharedBaseMapSource: Hashable, Sendable {
    case style(url: String)
    case raster(url: String, tileSize: Double)
}

struct SharedBaseMapDefinition: Identifiable, Hashable, Sendable {
    let id: String
    let label: String
    let source: SharedBaseMapSource
    let visibleByDefault: Bool
    let attribution: String?
}

struct SharedRasterOverlayDefinition: Identifiable, Hashable, Sendable {
    let id: String
    let label: String
    let url: String
    let tileSize: Double
    let visibleByDefault: Bool
    let opacity: Double
    let attribution: String?
}

enum SharedMapCatalog {
    static let baseMaps: [SharedBaseMapDefinition] = [
${baseMapRows}
    ]

    static let rasterOverlays: [SharedRasterOverlayDefinition] = [
${overlayRows}
    ]
}
`;

if (process.argv.includes('--check')) {
  const committedSwift = await readFile(swiftOutputPath, 'utf8').catch(
    () => '',
  );
  if (committedSwift !== generatedSwift) {
    throw new Error(
      'Generated Swift map catalogue is stale. Run pnpm map-catalog:generate.',
    );
  }
} else {
  await writeFile(swiftOutputPath, generatedSwift);
}
