on:
  schedule:
    - cron: "*/5 * * * *" # every 5 minutes
  workflow_dispatch:
jobs:
  drain_webhook_inbox:
    name: Drain Strava Webhook Inbox
    runs-on: ubuntu-22.04
    # No need for environment variables as we can access secrets directly
    steps:
      - name: Drain Webhook Inbox
        id: drainRequest
        uses: fjogeleit/http-request-action@v1
        with:
          method: "POST"
          url: "https://activitymap.dominik.page/api/cron/drain-webhook-inbox"
          customHeaders: '{"x-cron-secret": "${{ secrets.CRON_SECRET }}"}'
          timeout: 60000
      - name: Show Response
        run: |
          echo "Status: ${{ steps.drainRequest.outputs.status }}"
          echo "Response: ${{ steps.drainRequest.outputs.response }}"
