name: Pull and clean data

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 */3 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Pull data
      run: |
        mv activities_geo.json activities_geo.json.old
        curl https://us-central1-stravamap-386413.cloudfunctions.net/strava_geojson --output activities_geo.json
        diff activities_geo.json activities_geo.json.old || echo "No changes"
    - name: Commit new json file
      run: |
        git config --global user.name "wirhabenzeit"
        git config --global user.email "dschroeder@ethz.ch"
        git add activities_geo.json
        git commit -m "Updating activities_geo.json" || echo "No changes to commit"
        git push
    - name: Update Github pages
      run: |
        npm install
        npm run build
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: dist
