name: Pull and clean data

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'LICENSE'
      - 'README.md'
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 11,23 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Pull data
      run: |
        curl https://us-central1-stravamap-386413.cloudfunctions.net/strava_geojson --output activities_geo.json
    - name: Commit new json file
      run: |
        git config --global user.name "wirhabenzeit"
        git config --global user.email "dschroeder@ethz.ch"
        git add activities_geo.json
        git commit -m "Updating activities_geo.json" || echo "No changes to commit"
        git push
    - name: Update Github pages
      run: |
        npm run deploy
