name: Pull and clean data

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 */3 * * *'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup jq
      run: |
        sudo apt-get install -y jq
    - name: Pull data
      run: |
        mv public/activities_geo.json activities_geo.json.old
        curl https://us-central1-stravamap-386413.cloudfunctions.net/strava_geojson --output activities_geo_ugly.json
        jq . activities_geo_ugly.json > public/activities_geo.json
    - name: Check for changes
      run: |
        diff public/activities_geo.json activities_geo.json.old || echo "No changes"
    - name: Update Github pages
      run: |
        npm install
        npm run build
    - name: Commit new json file
      run: |
        git config --global user.name "wirhabenzeit"
        git config --global user.email "dschroeder@ethz.ch"
        git add public/activities_geo.json 
        git add dist*
        git commit -m "Updating activities_geo.json" || echo "No changes to commit"
        git push
    - name: Setup Pages
      uses: actions/configure-pages@v3
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: './dist'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1
