name: Refresh Token

on:
  schedule:
    - cron: "0 */3 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Call webhook to refresh token
        run: |
          curl "https://yvkdmnzwrhvjckzyznwu.supabase.co/functions/v1/strava-refresh"
